services:
    #pupflare:
    #    image: quay.io/unixfox/pupflare
    #    restart: always
    #    ports:
    #        - 8888:3000

    bot:
        #depends_on:
        #    - pupflare
        build:
            context: .
        restart: always
        environment:
            NODE_ENV: production

            # use pupflare service
            #BASE_URL: pupflare:8888/?url=https://apptoogoodtogo.com/api

            #Filepath
            TOKEN_FILEPATH: ./build/data
            TOKEN_FILENAME: tgtg_token.json

            COOKIE_FILEPATH: ./build/data
            COOKIE_FILENAME: tgtg_cookie.txt

        ports:
            - 8989:8989
        volumes:
            - authdata:/usr/src/app/build/data
volumes:
    authdata:
